# Regularizações / Coeficientes
- l1
- l2
- elasticnet

In [22]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [12]:
# https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data
df_wine = pd.read_csv('datasets/wine.data', header=None)


df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
                   'Alcalinity of ash', 'Magnesium', 'Total phenols',
                   'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
                   'Color intensity', 'Hue', 'OD280/OD315 of diluted wines',
                   'Proline']

print('Class labels', np.unique(df_wine['Class label']))
df_wine.head()

Class labels [1 2 3]


Class label  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0            1    14.23        1.71  2.43               15.6        127   
1            1    13.20        1.78  2.14               11.2        100   
2            1    13.16        2.36  2.67               18.6        101   
3            1    14.37        1.95  2.50               16.8        113   
4            1    13.24        2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185  
3             7.80  0.86                          3.45     1480  
4             4.32  1.04                          2.93      735

In [13]:
X, y = df_wine.iloc[:, 1:].values, df_wine.iloc[:, 0].values

X_train, X_test, y_train, y_test =\
    train_test_split(X, y, 
                     test_size=0.3, 
                     random_state=0, 
                     stratify=y)

In [15]:
stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

In [76]:
model_none = linear_model.LogisticRegression(penalty='l1', random_state=0)
model_none.fit(X_train_std, y_train)
y_pred = model_none.predict(X_test_std)
print('X.shape:{}'.format(X.shape))
print('np.unique(y):{}'.format(np.unique(y)))
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

X.shape:(178, 13)
np.unique(y):[1 2 3]
accuracy_score:1.0
intercept_:
[-1.26336366 -1.21618634 -2.37024246]
coef_:
[[ 1.24570162  0.18080713  0.74353603 -1.16136393  0.          0.
   1.17018229  0.          0.          0.          0.          0.54694578
   2.5105225 ]
 [-1.53703752 -0.38783998 -0.99522581  0.36515494 -0.05971764  0.
   0.6679069   0.          0.         -1.93444244  1.23318828  0.
  -2.23120752]
 [ 0.13569598  0.16855897  0.35714641  0.          0.          0.
  -2.43805494  0.          0.          1.56356741 -0.81860375 -0.4927206
   0.        ]]


In [80]:
model_none = linear_model.LogisticRegression(penalty='l2', random_state=0)
model_none.fit(X_train_std, y_train)
y_pred = model_none.predict(X_test_std)
print('X.shape:{}'.format(X.shape))
print('np.unique(y):{}'.format(np.unique(y)))
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

X.shape:(178, 13)
np.unique(y):[1 2 3]
accuracy_score:1.0
intercept_:
[-1.33509136 -0.96973542 -2.04898785]
coef_:
[[ 1.27713853  0.38210274  0.8015599  -1.30842842  0.22782837  0.23101419
   0.90234371 -0.08423823  0.01462196 -0.0312838   0.02796323  0.71703048
   1.79262118]
 [-1.45395571 -0.620303   -1.05445248  0.67148394 -0.29048951  0.18277571
   0.51163918  0.10789643  0.08199321 -1.61228834  0.88800662  0.1659356
  -1.73246957]
 [ 0.38965148  0.4083047   0.40211468  0.26242969  0.15288658 -0.20064653
  -1.38792256 -0.06305419 -0.28440345  1.2553389  -0.93849662 -0.83821807
   0.13754706]]


In [79]:
model_none = linear_model.LogisticRegression(multi_class='multinomial', solver='newton-cg', penalty='l2', random_state=0)
model_none.fit(X_train_std, y_train)
y_pred = model_none.predict(X_test_std)
print('X.shape:{}'.format(X.shape))
print('np.unique(y):{}'.format(np.unique(y)))
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

X.shape:(178, 13)
np.unique(y):[1 2 3]
accuracy_score:1.0
intercept_:
[ 0.36862533  0.78036204 -1.14898737]
coef_:
[[ 0.78792639  0.24089338  0.4473384  -0.73489829  0.1113343   0.22607273
   0.60652205 -0.14847572  0.24131476  0.14140959  0.10670518  0.58061102
   0.98240089]
 [-0.95393153 -0.43668273 -0.76795841  0.50646632 -0.17622299  0.07110642
   0.38809799  0.09343743  0.11353057 -0.91231356  0.61090399  0.16780023
  -1.10002567]
 [ 0.16600514  0.19578935  0.32062001  0.22843197  0.06488869 -0.29717916
  -0.99462004  0.05503829 -0.35484533  0.77090397 -0.71760916 -0.74841125
   0.11762478]]


In [66]:
model_none = linear_model.SGDClassifier(loss='modified_huber', penalty='none', random_state=0)
model_none.fit(X_train_std, y_train)
y_pred = model_none.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

accuracy_score:1.0
intercept_:
[-142.68148912 -125.44735328 -276.67748864]
coef_:
[[  90.2812871    36.64948258   97.04085794 -125.41752433  -28.19064734
    76.28288223   97.37681826  -41.40195898  -56.92549775   17.58870599
    27.37182208   73.34084621  211.19599252]
 [-263.95993746  -81.35192407 -134.50534288   85.42530184   40.65883345
     6.9551471   154.53036184  100.2277951   -28.48638801 -310.80926881
   114.21362832    7.64180817 -230.50397619]
 [ 135.67707929    4.84753801   85.28769102  100.2663828    -3.63503296
   -22.82533178 -171.25578945  -35.53445471  -51.06959705  152.05944999
  -176.79823346 -170.17637065   93.74735741]]


In [67]:
model_l1 = linear_model.SGDClassifier(loss='modified_huber', penalty='l1', random_state=0)
model_l1.fit(X_train_std, y_train)
y_pred = model_l1.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

accuracy_score:1.0
intercept_:
[-142.68148912 -125.44735328 -276.67748864]
coef_:
[[  90.2812871    36.64948258   97.04085794 -125.41752433  -28.19064734
    76.28288223   97.37681826  -41.40195898  -56.92549775   17.58870599
    27.37182208   73.34084621  211.19599252]
 [-263.95993746  -81.35192407 -134.50534288   85.42530184   40.65883345
     6.9551471   154.53036184  100.2277951   -28.48638801 -310.80926881
   114.21362832    7.64180817 -230.50397619]
 [ 135.67707929    4.84753801   85.28769102  100.2663828    -3.63503296
   -22.82533178 -171.25578945  -35.53445471  -51.06959705  152.05944999
  -176.79823346 -170.17637065   93.74735741]]


In [68]:
model_l2 = linear_model.SGDClassifier(loss='modified_huber', penalty='l2', random_state=0,)
model_l2.fit(X_train_std, y_train)
y_pred = model_l2.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

accuracy_score:0.9814814814814815
intercept_:
[-142.68148912 -125.44735328 -276.67748864]
coef_:
[[  90.2812871    36.64948258   97.04085794 -125.41752433  -28.19064734
    76.28288223   97.37681826  -41.40195898  -56.92549775   17.58870599
    27.37182208   73.34084621  211.19599252]
 [-263.95993746  -81.35192407 -134.50534288   85.42530184   40.65883345
     6.9551471   154.53036184  100.2277951   -28.48638801 -310.80926881
   114.21362832    7.64180817 -230.50397619]
 [ 135.67707929    4.84753801   85.28769102  100.2663828    -3.63503296
   -22.82533178 -171.25578945  -35.53445471  -51.06959705  152.05944999
  -176.79823346 -170.17637065   93.74735741]]


In [69]:
model = linear_model.SGDClassifier(loss='modified_huber', penalty='elasticnet', random_state=0)
model.fit(X_train_std, y_train)
y_pred = model.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

accuracy_score:1.0
intercept_:
[-142.68148912 -125.44735328 -276.67748864]
coef_:
[[  90.2812871    36.64948258   97.04085794 -125.41752433  -28.19064734
    76.28288223   97.37681826  -41.40195898  -56.92549775   17.58870599
    27.37182208   73.34084621  211.19599252]
 [-263.95993746  -81.35192407 -134.50534288   85.42530184   40.65883345
     6.9551471   154.53036184  100.2277951   -28.48638801 -310.80926881
   114.21362832    7.64180817 -230.50397619]
 [ 135.67707929    4.84753801   85.28769102  100.2663828    -3.63503296
   -22.82533178 -171.25578945  -35.53445471  -51.06959705  152.05944999
  -176.79823346 -170.17637065   93.74735741]]


In [60]:
np.unique(y)

array([1, 2, 3])

In [61]:
# loss: 'hinge', 'log', 'modified_huber', 'squared_hinge', 'perceptron', or a 
# regression loss: 'squared_loss', 'huber', 'epsilon_insensitive', or 'squared_epsilon_insensitive'