In [1]:
import numpy as np
from sklearn import metrics

In [2]:
y = ['cat', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat', 
     'dog', 'dog', 'dog', 'dog', 'dog', 'dog',
     'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit',
     'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit']

In [3]:
y_pred = ['cat', 'cat', 'cat', 'cat', 'cat', 'dog', 'dog', 'dog', 
     'cat', 'cat', 'dog', 'dog', 'dog', 'rabbit',
     'dog', 'dog', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit',
     'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit']

In [4]:
cm = metrics.confusion_matrix(y, y_pred, labels=['cat', 'dog', 'rabbit'])
print(cm)

[[ 5  3  0]
 [ 2  3  1]
 [ 0  2 11]]


## Accuracy

In [5]:
metrics.accuracy_score(y, y_pred)

0.7037037037037037

In [11]:
accuracy = np.sum(np.diagonal(cm)) / np.sum(cm)
print(accuracy)

0.7037037037037037


## Precision

In [15]:
metrics.precision_score(y, y_pred, average=None)

array([0.71428571, 0.375     , 0.91666667])

### P = TP / (TP + FP) 

In [19]:
5 / (5 + 2 + 0)

0.7142857142857143

In [24]:
for c in range(cm.shape[0]):
    print(cm[c,c] / np.sum(cm[:, c]))

0.7142857142857143
0.375
0.9166666666666666


## Recall

In [16]:
metrics.recall_score(y, y_pred, average=None)

array([0.625     , 0.5       , 0.84615385])

### R = TP / (TP + FN) 

In [20]:
5 / (5 + 3 + 0)

0.625

In [25]:
for l in range(cm.shape[0]):
    print(cm[l,l] / np.sum(cm[l, :]))

0.625
0.5
0.8461538461538461


In [18]:
print(metrics.classification_report(y, y_pred))

              precision    recall  f1-score   support

         cat       0.71      0.62      0.67         8
         dog       0.38      0.50      0.43         6
      rabbit       0.92      0.85      0.88        13

   micro avg       0.70      0.70      0.70        27
   macro avg       0.67      0.66      0.66        27
weighted avg       0.74      0.70      0.72        27



In [26]:
metrics.log_loss(y, y_pred)

/Users/regis/miniconda3/envs/ml/lib/python3.7/site-packages/sklearn/utils/validation.py:563: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  FutureWarning)


TypeError: ufunc 'minimum' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')