# Tutorial Regressão Linear Simples usando o Numpy

In [1]:
import numpy as np

## Linha reta de uma regressão linear simples



$$ y = w_0 + w_1 \cdot x $$

In [ ]:
# $$ mean(x) = \frac { \sum_{i=1}^n { x_i } } { count(x) } $$

## Média

$$ mean(x) = \frac { \sum_{i=1}^n { x_i } } { count(x) } $$

In [2]:
x = np.array([ 1, 2, 4, 3, 5 ])
y = np.array([ 1, 3, 3, 2, 5 ])

In [3]:
mean_x = np.mean(x)
mean_x

3.0

In [4]:
mean_y = np.mean(y)
mean_y

2.8

In [6]:
# w_1 = \frac { \sum_{i=1}^n ((x_i - mean(x)) \cdot (y_i - mean(y))) } 
# { \sum_{i=1}^n (x_i - mean(x))^2 }

# Cálculo dos coeficientes

$$ w_1 = \frac { \sum_{i=1}^n ((x_i - mean(x)) \cdot (y_i - mean(y))) } { \sum_{i=1}^n (x_i - mean(x))^2 } $$

In [5]:
n = x.shape[0]
n

5

In [7]:
x - mean_x

array([-2., -1.,  1.,  0.,  2.])

In [8]:
y - mean_y

array([-1.8,  0.2,  0.2, -0.8,  2.2])

In [9]:
sum1 = np.sum( (x - mean_x) * (y - mean_y) )
sum2 = np.sum( (x - mean_x) ** 2 )
w1 = sum1 / sum2
w1

0.8

$$ w_0 = mean(y) - w_1 \cdot mean(x) $$

In [10]:
w0 = mean_y - w1 * mean_x
w0

0.39999999999999947

## Predição

In [11]:
def predict(x):
    return w0 + w1 * x

In [12]:
y_pred = predict(x)
y_pred

array([1.2, 2. , 3.6, 2.8, 4.4])

In [13]:
y

array([1, 3, 3, 2, 5])

In [16]:
def mse(y, y_pred):
    return np.sum(( y - y_pred ) ** 2)

In [17]:
mse(y, y_pred)

2.400000000000001

In [18]:
def rmse(y, y_pred):
    return mse(y, y_pred) ** 0.5

In [19]:
rmse(y, y_pred)

1.549193338482967

In [21]:
class RegressaoLinearSimples:

    def fit(self, x, y):
        mean_x = np.mean(x)
        mean_y = np.mean(y)
        sum1 = np.sum( (x - mean_x) * (y - mean_y) )
        sum2 = np.sum( (x - mean_x) ** 2 )
        self.w1 = sum1 / sum2
        self.w0 = mean_y - self.w1 * mean_x

    def predict(self, x):
        return self.w0 + self.w1 * x

In [22]:
model = RegressaoLinearSimples()

In [23]:
model.fit(x, y)

In [24]:
y_pred = model.predict(x)

In [25]:
y_pred

array([1.2, 2. , 3.6, 2.8, 4.4])